FROM node:18-alpine

WORKDIR /usr/src/app

# Copy and install dependencies
COPY package*.json ./
RUN npm ci

# Copy all source code
COPY . .

# Build TypeScript
RUN npm run build

# Expose your app port
EXPOSE 3004

# Run the compiled JavaScript
CMD ["node", "dist/index.js"]
